name: agrivision
description: AI-Powered Agricultural Assistant for farmers and agronomists

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  permission_handler: ^11.3.0
  flutter_image_compress: ^2.1.0
  flutter:
    sdk: flutter

  # UI & Fonts
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1

  # Supabase
  supabase_flutter: ^2.10.3

  # Camera & Images
  camera: ^0.10.5
  image_picker: ^1.1.2
  image: ^4.1.3

  # HTTP & Network
  http: ^1.2.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.18.1

  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Charts
  fl_chart: ^0.65.0

  # Loading indicators
  shimmer: ^3.0.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add assets here
  # assets:
  #   - assets/images/
  #   - assets/models/
